### ISSUE TITLE
The app won't connect to the game

### ISSUE THREAD

**Issue by FIR3W0LF** [LennysLounge/ACC-Race-Control#30]
Hello, since I unpdated Race control to the 1.5.7 version, I tried to input the settings manually but it does not connect to the game.
(the auto detect setting function does not work but I now why, the Documents directory is not on the C: disk)

here is a part of the log report (because I clicked multiple times on connect, many lines are the same).

```
[20240923-10:37:18-846] INFO    Animation Thread     ConnectionController.connectButtonPressed()            : Connect button pressed
[20240923-10:37:18-847] INFO    Animation Thread     ConnectionController.connectWithInput()                : Try connecting with input
[20240923-10:37:18-849] SEVERE  Animation Thread     ConnectionController.connectWithInput()                : Error starting the connection to the game.
java.net.BindException: Cannot assign requested address: Cannot bind
	at java.base/java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
	at java.base/java.net.DualStackPlainDatagramSocketImpl.bind0(DualStackPlainDatagramSocketImpl.java:84)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:117)
	at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:395)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:245)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:199)
	at racecontrol.client.AccConnection.<init>(AccConnection.java:128)
	at racecontrol.client.AccBroadcastingClient.connect(AccBroadcastingClient.java:177)
	at racecontrol.gui.app.settings.connection.ConnectionController.connectWithInput(ConnectionController.java:138)
	at racecontrol.gui.app.settings.connection.ConnectionController.connectButtonPressed(ConnectionController.java:70)
	at racecontrol.gui.lpui.LPButton.onMousePressed(LPButton.java:84)
	at racecontrol.gui.lpui.LPComponent.onMousePressedInternal(LPComponent.java:382)
	at racecontrol.gui.lpui.LPContainer.onMousePressedInternal(LPContainer.java:72)
	at racecontrol.gui.lpui.LPContainer.onMousePressedInternal(LPContainer.java:72)
	at racecontrol.gui.lpui.LPContainer.onMousePressedInternal(LPContainer.java:72)
	at racecontrol.gui.lpui.LPBase.mousePressed(LPBase.java:57)
	at processing.core.PApplet.mousePressed(PApplet.java:2757)
	at processing.core.PApplet.handleMouseEvent(PApplet.java:2690)
	at processing.core.PApplet.dequeueEvents(PApplet.java:2607)
	at processing.core.PApplet.handleDraw(PApplet.java:2448)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```

**Comment by FIR3W0LF** [comment]
after a bit of testing, it seems the issue is caused by the use of a VPN with Race Control. It seems to be blocking the connection to the game.
